### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ltspicer** [DoctorW00/SFDLSaugerPro#1]
Do you have a tutorial for installation?
I make:

sudo apt install build-essential perl python git
sudo apt install qt5-default libqt5multimedia5 qtmultimedia5-dev
mkdir sauger
cd sauger
git clone git://code.qt.io/qt/qtftp.git
cd qtftp
qmake
make
>> I get the following error:
.
.
.
cd qftp/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/treki/sauger/qtftp/examples/qftp/qftp.pro ) && make -f Makefile 
Project ERROR: You cannot build examples inside the Qt source tree, except as part of a proper Qt build.
make[1]: *** [Makefile:47: sub-qftp-make_first] Fehler 3
make[1]: Verzeichnis „/home/treki/sauger/qtftp/examples“ wird verlassen
make: *** [Makefile:74: sub-examples-make_first] Fehler 2

My OS is Linux Mint 20 mate

**Comment by DoctorW00** [comment]
For Ubuntu 20.10 it would be like this:

sudo apt install build-essential perl python git
sudo apt install qt5-default libqt5multimedia5 qtmultimedia5-dev *qt5*dev*
mkdir sauger
cd sauger
git clone git://code.qt.io/qt/qtftp.git
cd qtftp
qmake
make
sudo make install
sudo apt install unrar
cd ..
git clone https://github.com/DoctorW00/SFDLSaugerPro.git
cd SFDLSaugerPro
qmake
make -j4
./SFDLSaugerPro

**Comment by ltspicer** [comment]
$ sudo apt install qt5-default libqt5multimedia5 qtmultimedia5-dev qt5dev*
E: Paket qt5dev* kann nicht gefunden werden.

$ make
make[1]: Verzeichnis „/home/treki/sauger/qtftp/examples“ wird betreten
cd qftp/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/treki/sauger/qtftp/examples/qftp/qftp.pro ) && make -f Makefile 
Project ERROR: You cannot build examples inside the Qt source tree, except as part of a proper Qt build.
make[1]: *** [Makefile:47: sub-qftp-make_first] Fehler 3
make[1]: Verzeichnis „/home/treki/sauger/qtftp/examples“ wird verlassen
make: *** [Makefile:74: sub-examples-make_first] Fehler 2

**Comment by DoctorW00** [comment]
Sorry, it is  *qt5*dev* ... for some reason c&p did fail on me.

**Comment by DoctorW00** [comment]
OK, for some reason there is always only one * ... check out https://mlcboard.com/forum/showthread.php?402003 for the correct one, guess some github issue.
